name: "Label PRs"

on:
  pull_request:
    types: [synchronize, closed]

jobs:
  labelPR:
    runs-on: ubuntu-latest
    if: ${{ github.event.action != 'closed' }}
    steps:
    - name: Label 'in progress'
      uses: actions/github-script@v4
      with:
        github-token: ${{secrets.LABEL_PULL_REQUEST}}
        script: |
          github.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['in progress']
          })

  unlabelPR:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'closed' }}
    steps:
    - name: Remove 'ready for review' label
      uses: actions/github-script@v4
      with:
        github-token: ${{secrets.LABEL_PULL_REQUEST}}
        script: |
          github.issues.removeLabel({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: 'ready for review'
          })
