name: "Label PRs"

on:
  pull_request:
    types: [synchronize]

jobs:
  labelPR:
    runs-on: ubuntu-latest
    steps:
    - name: Label 'in progress'
      uses: actions/github-script@v4
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['in progress']
          })
